disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID: ''

menu:
- {name: 'Home', path: '.', url: 'index.html'}
- {name: 'Research', path: 'menu', url: 'research.html'}
- {name: 'Honors/Funding', path: 'menu', url: 'funding.html'}
- {name: 'Industry', path: 'menu', url: 'industry.html'}
- {name: 'Education', path: 'menu', url: 'education.html'}
- {name: 'CV', path: 'menu', url: 'mycv.html'}

social:
- {icon: 'google-scholar', link: 'https://scholar.google.com/citations?user=5fqoqisAAAAJ'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/sebastian-gabel-800906168/'}
- {icon: 'github', link: 'https://www.github.com/sbstn-gbl'}
- {icon: 'orcid', link: 'https://orcid.org/0000-0003-3522-2263'}
- {icon: 'envelope', link: 'mailto:gabel@rsm.nl'}

cv_pdf: /assets/cv/gabel-cv-web-2025-12.pdf

pagination:
  next_page: 'Newer'
  previous_page: 'Older'
sharing_button_prompt: 'Feel free to share!'
related_posts: 'You may also enjoy:'
post_date_prefix: 'Written on'
